directive @Permissions(types: [String]!) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION | OBJECT

directive @isAuthenticated on OBJECT | FIELD_DEFINITION

directive @CacheControl(maxAge: Int, scope: CacheControlScope) on FIELD_DEFINITION | OBJECT | INTERFACE

directive @NoCache on FIELD_DEFINITION | OBJECT | INTERFACE

directive @cacheWarming on QUERY

directive @condenseCache on QUERY

directive @defer(if: Boolean, label: String) on FRAGMENT_SPREAD | INLINE_FRAGMENT

directive @IntRange(min: Int, max: Int) on INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION

directive @recomposeCache on QUERY

directive @stream(if: Boolean, label: String, initialCount: Int = 0) on FIELD

enum RegisteredDeviceTypeEnum {
  """Browser"""
  BROWSER
  """Android"""
  ANDROID
  """iOS"""
  IOS
}

input RegisterDeviceInput {
  userAgent: String
  type: RegisteredDeviceTypeEnum!
}

"""Represents a Device in the system"""
type Device {
  """The Devices ID"""
  id: ID!
  """The Devices type"""
  type: RegisteredDeviceTypeEnum!
  """The devices UserAgent String"""
  userAgent: String
  userDevices: [UserDevice!]!
  """The creation date of the Device"""
  createdAt: DateTime
  """The update date of the Device"""
  updatedAt: DateTime
}

"""Properties list object"""
type DeviceList {
  """A list of Properties"""
  list: [Device]!
  """A count of Properties"""
  count: Int!
  """Number of Device records skipped"""
  skip: Int!
  """Number of Device records returned"""
  limit: Int!
}

type DeviceInfo {
  id: ID!
  isBot: Boolean!
}

input FileUploadInput {
  file: Upload!
  name: String!
  categories: [ID]
}

"""Represents a File in the system"""
interface File {
  """The File's ID"""
  id: ID!
  name: String!
  location: String!
  mimetype: String!
  extension: String!
  categories: [FileCategory]
  """The creation date of the Model"""
  createdAt: DateTime
  """The update date of the Model"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum FileOrderEnum {
  """Name"""
  NAME
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""File filtering options"""
input FileFilters {
  search: String
  id: ID
  ids: [ID!]
  categories: [ID]
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
}

"""File ordering options"""
input FileOrder {
  """Order field"""
  field: FileOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type FileList {
  """A list of Properties"""
  list: [File]!
  """A count of Properties"""
  count: Int!
  """Number of File records skipped"""
  skip: Int!
  """Number of File records returned"""
  limit: Int!
}

"""Represents a FileCategory in the system"""
type FileCategory {
  """The FileCategory's ID"""
  id: ID!
  name: String!
  files: [File]
  """The creation date of the FileCategory"""
  createdAt: DateTime
  """The update date of the FileCategory"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum FileCategoryOrderEnum {
  """Name"""
  NAME
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""FileCategory filtering options"""
input FileCategoryFilters {
  search: String
  id: ID
  ids: [ID!]
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
}

"""FileCategory ordering options"""
input FileCategoryOrder {
  """Order field"""
  field: FileCategoryOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type FileCategoryList {
  """A list of Properties"""
  list: [FileCategory]!
  """A count of Properties"""
  count: Int!
  """Number of FileCategory records skipped"""
  skip: Int!
  """Number of FileCategory records returned"""
  limit: Int!
}

"""Fields to add a new FileCategory"""
input AddFileCategoryInput {
  name: String!
}

"""Fields to update an existing FileCategory"""
input UpdateFileCategoryInput {
  name: String
}

enum ImageScaleEnum {
  """Scale to Cover"""
  COVER
  """Scale to Fit"""
  FIT
  """Scale to Contain"""
  CONTAIN
}

enum ImageEncodingEnum {
  """WebP"""
  WEBP
  """PNG"""
  PNG
  """JPEG"""
  JPEG
  """SVG"""
  SVG
}

enum ImageTransformTypeEnum {
  """Blur"""
  BLUR
  """Gaussian Blur"""
  GAUSSIAN_BLUR
  """Grey Scale"""
  GREY_SCALE
  """Posterize"""
  POSTERIZE
  """Sepia"""
  SEPIA
  """Pixelate"""
  PIXELATE
  """Opacity"""
  OPACITY
  """CMYK Color Space"""
  CMYK
}

input ImageTransform {
  type: ImageTransformTypeEnum!
  value: Float
}

type ImageInfo {
  type: String!
  width: Int!
  height: Int!
}

"""Represents a Image in the system"""
type Image implements File {
  """The Image's ID"""
  id: ID!
  name: String!
  alt: String!
  staticId: String
  location: String!
  mimetype: String!
  extension: String!
  encoding: ImageEncodingEnum!
  imageInfo: ImageInfo!
  categories: [FileCategory]
  hasTransparency: Boolean!
  isVector: Boolean!
  isDefault: Boolean!
  url(width: Int, height: Int, scale: ImageScaleEnum, transforms: [ImageTransform], encoding: ImageEncodingEnum): URI
  """The creation date of the Image"""
  createdAt: DateTime
  """The update date of the Image"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum ImageOrderEnum {
  """Name"""
  NAME
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""Image filtering options"""
input ImageFilters {
  search: String
  id: ID
  ids: [ID!]
  categories: [ID]
  encoding: [ImageEncodingEnum!]
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
}

"""Image ordering options"""
input ImageOrder {
  """Order field"""
  field: ImageOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type ImageList {
  """A list of Properties"""
  list: [Image]!
  """A count of Properties"""
  count: Int!
  """Number of Image records skipped"""
  skip: Int!
  """Number of Image records returned"""
  limit: Int!
}

"""Fields to add a new Image"""
input AddImageInput {
  name: String!
  alt: String
  staticId: String
  file: Upload!
  categories: [ID]
  hasTransparency: Boolean
}

"""Fields to update an existing Image"""
input UpdateImageInput {
  name: String
  alt: String
  staticId: String
  categories: [ID]
  hasTransparency: Boolean
}

"""The type of permission"""
enum PermissionTypeEnum {
  """Static Permission (Specified in Code)"""
  STATIC_PERMISSION
  """Dynamic Permission (Specified in Schema)"""
  DYNAMIC_PERMISSION
}

"""Represents a Permission in the system"""
type Permission {
  """The Permission's ID"""
  id: ID!
  name: String!
  identifier: String!
  description: String!
  roles: [Role]
  isOwned: Boolean
  objectType: String
  """The creation date of the Model"""
  createdAt: DateTime
  """The update date of the Model"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum PermissionOrderEnum {
  """Name"""
  NAME
  TYPE
  MODULE
  OBJECT_TYPE
}

"""Permission filtering options"""
input PermissionFilters {
  id: ID
  ids: [ID!]
  search: String
  types: [PermissionTypeEnum]
}

"""Permission ordering options"""
input PermissionOrder {
  """Order field"""
  field: PermissionOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type PermissionList {
  """A list of Properties"""
  list: [Permission]!
  """A count of Properties"""
  count: Int!
  """Number of Permission records skipped"""
  skip: Int!
  """Number of Permission records returned"""
  limit: Int!
}

"""Represents a Role in the system"""
type Role {
  """The Role's ID"""
  id: ID!
  name: String!
  description: String
  permissions: [Permission]
  users: [UserRole]
  """The creation date of the Role"""
  createdAt: DateTime
  """The update date of the Role"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum RoleOrderEnum {
  """Name"""
  NAME
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""Role filtering options"""
input RoleFilters {
  search: String
  id: ID
  ids: [ID!]
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
}

"""Role ordering options"""
input RoleOrder {
  """Order field"""
  field: RoleOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type RoleList {
  """A list of Properties"""
  list: [Role]!
  """A count of Properties"""
  count: Int!
  """Number of Role records skipped"""
  skip: Int!
  """Number of Role records returned"""
  limit: Int!
}

"""Fields to add a new Role"""
input AddRoleInput {
  name: String!
  description: String
  permissions: [String]
}

"""Fields to update an existing Role"""
input UpdateRoleInput {
  name: String
  description: String
  permissions: [String]
  updatedAt: DateTime
}

"""A Users Title"""
enum TitleEnum {
  """Mr"""
  MR
  """Ms"""
  MS
  """Mrs"""
  MRS
}

"""Represents a User in the system"""
interface User {
  """The User's ID"""
  id: ID!
  title: TitleEnum
  firstName: String!
  lastName: String!
  name: String!
  email: Email!
  emailIsVerified: Boolean
  userDevices: [UserDevice]
  userRoles: [UserRole]
  currentDevice: Device
  """The creation date of the User"""
  createdAt: DateTime
  """The update date of the User"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum UserOrderEnum {
  """First Name"""
  FIRST_NAME
  """Last Name"""
  LAST_NAME
  """Name"""
  NAME
  EMAIL
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""User filtering options"""
input UserFilters {
  id: ID
  ids: [ID!]
  search: String
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
  hasAcceptedInvite: Boolean
  isInvited: Boolean
}

"""User ordering options"""
input UserOrder {
  """Order field"""
  field: UserOrderEnum!
  """Order direction"""
  direction: OrderDirectionEnum!
}

"""Properties list object"""
type UserList {
  """A list of Properties"""
  list: [User]!
  """A count of Properties"""
  count: Int!
  """Number of User records skipped"""
  skip: Int!
  """Number of User records returned"""
  limit: Int!
}

"""Represents a UserDevice in the system"""
type UserDevice {
  """The UserDevice's ID"""
  id: ID!
  active: Boolean!
  user: User!
  device: Device!
  """The creation date of the UserDevice"""
  createdAt: DateTime
  """The update date of the UserDevice"""
  updatedAt: DateTime
}

"""Represents a UserRole in the system"""
type UserRole {
  """The UserRole's ID"""
  id: ID!
  user: User!
  role: Role!
  """The creation date of the UserRole"""
  createdAt: DateTime
  """The update date of the UserRole"""
  updatedAt: DateTime
}

"""Fields available to order Properties"""
enum UserRoleOrderEnum {
  """Name"""
  NAME
  """Created At"""
  CREATED_AT
  """Updated At"""
  UPDATED_AT
}

"""UserRole filtering options"""
input UserRoleFilters {
  search: String
  id: ID
  ids: [ID!]
  users: [ID!]
  roles: [ID!]
  minCreatedAt: DateTime
  maxCreatedAt: DateTime
  createdAt: DateTime
  minUpdatedAt: DateTime
  maxUpdatedAt: DateTime
  updatedAt: DateTime
}

"""UserRole ordering options"""
input UserRoleOrder {
  """Order field"""
  field: UserRoleOrderEnum
  """Order direction"""
  direction: OrderDirectionEnum
}

"""Properties list object"""
type UserRoleList {
  """A list of Properties"""
  list: [UserRole]!
  """A count of Properties"""
  count: Int!
  """Number of UserRole records skipped"""
  skip: Int!
  """Number of UserRole records returned"""
  limit: Int!
}

"""Fields to add a new UserRole"""
input AddUserRoleInput {
  user: ID!
  role: ID!
}

input UpdateUserRoleInput {
  user: ID!
  role: ID!
}

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

enum ApiScalarDataTypeEnum {
  """Integer"""
  INT
  """Float"""
  FLOAT
  """Double"""
  DOUBLE
  """Boolean"""
  BOOLEAN
  """Date"""
  DATE
  """Date Time"""
  DATE_TIME
  """Time"""
  TIME
  """Week"""
  WEEK
  """Month"""
  MONTH
  """Year"""
  YEAR
  """String"""
  STRING
  """Text"""
  TEXT
  """Hyper Text"""
  HYPERTEXT
  """Email"""
  EMAIL
  """Phone"""
  PHONE
  """Color"""
  COLOR
  """Link"""
  URI
}

"""Chronological Period Type"""
enum ChronologicalPeriodTypeEnum {
  """Daily"""
  DAILY
  """Weekly"""
  WEEKLY
  """Monthly"""
  MONTHLY
  """Yearly"""
  YEARLY
}

"""Chronological Unit Type"""
enum ChronologicalUnitTypeEnum {
  """Minute(s)"""
  MINUTE
  """Hour(s)"""
  HOUR
  """Day(s)"""
  DAY
  """Week(s)"""
  WEEK
  """Month(s)"""
  MONTH
  """Year(s)"""
  YEAR
}

"""Week Days"""
enum WeekDayEnum {
  """Monday"""
  MONDAY
  """Tuesday"""
  TUESDAY
  """Wednesday"""
  WEDNESDAY
  """Thursday"""
  THURSDAY
  """Friday"""
  FRIDAY
  """Saturday"""
  SATURDAY
  """Sunday"""
  SUNDAY
}

"""Month Weeks"""
enum MonthWeekEnum {
  """1st"""
  FIRST
  """2nd"""
  SECOND
  """3rd"""
  THIRD
  """4th"""
  FOURTH
}

"""YearMonths"""
enum YearMonthsEnum {
  """January"""
  JANUARY
  """February"""
  FEBRUARY
  """March"""
  MARCH
  """April"""
  APRIL
  """May"""
  MAY
  """June"""
  JUNE
  """July"""
  JULY
  """August"""
  AUGUST
  """September"""
  SEPTEMBER
  """October"""
  OCTOBER
  """November"""
  NOVEMBER
  """December"""
  DECEMBER
}

enum OrderDirectionEnum {
  """Order Ascending"""
  ASC
  """Order Descending"""
  DESC
}

enum UnitTypeEnum {
  """Kilogram"""
  KG
  """Gram"""
  G
  """Milligram"""
  MG
  """Litre"""
  L
  """Milliliter"""
  ML
  """Portion"""
  PORTION
  """Pinch"""
  PINCH
  """Unit"""
  UNIT
  """Table Spoon"""
  TBSP
  """Tea Spoon"""
  TSP
  """Piece"""
  PIECE
  """Drained Gram"""
  DG
}

input CacheKeyInput {
  type: String!
  id: ID
}

type EnumValue {
  title: String!
  value: String!
}

type EnumDescription {
  name: String!
  description: String!
  values: [EnumValue]
}

type ClientInterfaceType {
  name: String!
}

type ClientInterface {
  kind: String!
  name: String!
  possibleTypes: [ClientInterfaceType]
}

scalar Color

scalar Date

scalar DateTime

scalar Domain

scalar Email

scalar ExpiryMonth

scalar ExpiryYear

scalar JSON

scalar JSONObject

scalar JWT

scalar Password

scalar Phone

scalar Point

scalar Time

scalar URI

scalar Upload

type Query {
  """Get a list of Files with order and filtering options"""
  allFiles(skip: Int, limit: Int, filters: FileFilters, order: [FileOrder]): FileList!
  """Get a specific File by ID"""
  oneFile(id: ID!): File!
  """Get a count of File with filtering options"""
  countFiles(filters: FileFilters): Int!
  """Get a list of FileCategory with order and filtering options"""
  allFileCategories(skip: Int, limit: Int, filters: FileCategoryFilters, order: [FileCategoryOrder]): FileCategoryList!
  """Get a specific FileCategory by ID"""
  oneFileCategory(id: ID!): FileCategory!
  """Get a count of FileCategory with filtering options"""
  countFileCategories(filters: FileCategoryFilters): Int!
  """Get a list of Image with order and filtering options"""
  allImages(skip: Int, limit: Int, filters: ImageFilters, order: [ImageOrder]): ImageList!
  """Get a specific Image by ID"""
  oneImage(id: ID!): Image!
  """Get a count of Image with filtering options"""
  countImages(filters: ImageFilters): Int!
  """Get one stati image by identifier"""
  staticImage(id: ID): Image!
  """Get a list of Permissions with order and filtering options"""
  allPermissions(skip: Int, limit: Int, filters: PermissionFilters, order: [PermissionOrder]): PermissionList!
  """Get a specific Permission by ID"""
  onePermission(id: ID!): Permission!
  """Get a count of Permission with filtering options"""
  countPermissions(filters: PermissionFilters): Int!
  """Get a list of Role with order and filtering options"""
  allRoles(skip: Int, limit: Int, filters: RoleFilters, order: [RoleOrder]): RoleList!
  """Get a specific Role by ID"""
  oneRole(id: ID!): Role!
  """Get a count of Role with filtering options"""
  countRoles(filters: RoleFilters): Int!
  """Get a list of User with order and filtering options"""
  allUsers(skip: Int, limit: Int, filters: UserFilters, order: [UserOrder]): UserList!
  """Get a specific User by ID"""
  oneUser(id: ID!): User!
  """Get a count of User with filtering options"""
  countUsers(filters: UserFilters): Int!
  """Validate User Invite"""
  validateInvite(token: JWT): User
  """Get a list of UserRole with order and filtering options"""
  allUserRoles(skip: Int, limit: Int, filters: UserRoleFilters, order: [UserRoleOrder]): UserRoleList!
  """Get a specific UserRole by ID"""
  oneUserRole(id: ID!): UserRole!
  """Get a count of UserRole with filtering options"""
  countUserRoles(filters: UserRoleFilters): Int!
  currentUser: User
  getEnums(enums: [String]!): [EnumDescription]
  getEnum(enum: String!): EnumDescription
  getInputObjectConfig(name: String!): JSON
  getDetailedInputObjectConfig(name: String!): JSON
  getInterfaceTypes: [ClientInterface]
}

type Mutation {
  """Register a new Device"""
  registerDevice(input: RegisterDeviceInput!): DeviceInfo!
  """Validate an existing device"""
  validateDevice(token: String!): DeviceInfo
  """Add a new FileCategory"""
  addFileCategory(input: AddFileCategoryInput!): FileCategory!
  """Update an existing FileCategory"""
  updateFileCategory(id: ID!, input: UpdateFileCategoryInput!): FileCategory!
  """Delete a FileCategory"""
  removeFileCategory(id: ID!): ID!
  """Add a new Image"""
  addImage(input: AddImageInput!): Image!
  """Update an existing Image"""
  updateImage(id: ID!, input: UpdateImageInput!): Image!
  """Delete a Image"""
  removeImage(id: ID!): ID!
  """Add a new Role"""
  addRole(input: AddRoleInput!): Role!
  """Update an existing Role"""
  updateRole(id: ID!, input: UpdateRoleInput!): Role!
  """Delete a Role"""
  removeRole(id: ID!): ID!
  """Give a Role a permission"""
  assignPermission(id: ID!, permissionId: ID!): Boolean!
  """Remove a permission from a role"""
  unassignPermission(id: ID!, permissionId: ID!): Boolean!
  """Add a new UserRole"""
  addUserRole(input: AddUserRoleInput!): UserRole!
  """Delete a UserRole"""
  removeUserRole(id: ID!): ID!
  """Update an existing UserRole - FAKE code gen method DO NOT USE """
  updateUserRole(id: ID!, input: UpdateUserRoleInput!): UserRole!
  clearCacheKeys(cacheKeys: [CacheKeyInput!]!): Boolean!
  clearAllCacheKeys: Boolean!
}